# Generated by Django 5.1.7 on 2025-04-01 10:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lms_system", "0003_alter_lesson_course"),
        ("users", "0002_alter_customuser_managers"),
    ]

    operations = [
        migrations.CreateModel(
            name="Payments",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "payment_date",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Укажите дату и время оплаты",
                        verbose_name="Дата и время оплаты:",
                    ),
                ),
                (
                    "payment_amount",
                    models.FloatField(
                        help_text="Укажите сумму платежа", verbose_name="Сумма платежа:"
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[("transfer", "Перевод на счет"), ("cash", "Наличные")],
                        max_length=100,
                    ),
                ),
                (
                    "paid_course",
                    models.ForeignKey(
                        blank=True,
                        help_text="Укажите оплаченный курс",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="courses",
                        to="lms_system.course",
                        verbose_name="Оплаченный курс:",
                    ),
                ),
                (
                    "paid_lesson",
                    models.ForeignKey(
                        blank=True,
                        help_text="Укажите оплаченный урок",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lessons",
                        to="lms_system.lesson",
                        verbose_name="Оплаченный урок:",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="Укажите пользователя",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="users",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь:",
                    ),
                ),
            ],
            options={
                "verbose_name": "Платеж",
                "verbose_name_plural": "Платежи",
                "ordering": ["payment_date"],
            },
        ),
    ]
