# Generated by Django 5.1.7 on 2025-04-01 10:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lms_system", "0003_alter_lesson_course"),
        ("users", "0003_payments"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payments",
            name="paid_course",
            field=models.ForeignKey(
                blank=True,
                help_text="Укажите оплаченный курс",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payments_for_courses",
                to="lms_system.course",
                verbose_name="Оплаченный курс:",
            ),
        ),
        migrations.AlterField(
            model_name="payments",
            name="paid_lesson",
            field=models.ForeignKey(
                blank=True,
                help_text="Укажите оплаченный урок",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payments_for_lessons",
                to="lms_system.lesson",
                verbose_name="Оплаченный урок:",
            ),
        ),
        migrations.AlterField(
            model_name="payments",
            name="user",
            field=models.ForeignKey(
                blank=True,
                help_text="Укажите пользователя",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payments",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь:",
            ),
        ),
    ]
