# Generated by Django 5.1.7 on 2025-04-03 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_payments_paid_course_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="payments",
            options={"verbose_name": "Платеж", "verbose_name_plural": "Платежи"},
        ),
        migrations.AlterField(
            model_name="payments",
            name="payment_method",
            field=models.CharField(
                choices=[("transfer", "Перевод на счет"), ("cash", "Наличные")],
                help_text="Укажите метод платежа",
                max_length=100,
                verbose_name="Метод платежа:",
            ),
        ),
    ]
