# Generated by Django 5.1.7 on 2025-08-07 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_alter_payments_options_alter_payments_payment_method"),
    ]

    operations = [
        migrations.AddField(
            model_name="payments",
            name="payment_url",
            field=models.URLField(
                blank=True,
                max_length=400,
                null=True,
                verbose_name="Созданная сессия для получения ссылки на оплату продукта в Stripe:",
            ),
        ),
        migrations.AddField(
            model_name="payments",
            name="stripe_price_id",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Созданная цена в платежной системе Stripe:",
            ),
        ),
        migrations.AddField(
            model_name="payments",
            name="stripe_product_id",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Созданный продукт в платежной системе Stripe:",
            ),
        ),
        migrations.AddField(
            model_name="payments",
            name="stripe_session_id",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Созданная сессия в платежной системе Stripe:",
            ),
        ),
    ]
