# Generated by Django 5.1.7 on 2025-08-07 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_payments_payment_url_payments_stripe_price_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payments",
            name="payment_url",
            field=models.URLField(
                blank=True,
                max_length=400,
                null=True,
                verbose_name="Ссылка на оплату продукта:",
            ),
        ),
        migrations.AlterField(
            model_name="payments",
            name="stripe_session_id",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Созданная сессия для получения ссылки в платежной системе Stripe:",
            ),
        ),
    ]
