# Generated by Django 5.1.7 on 2025-08-08 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_alter_payments_payment_url_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="payments",
            name="payment_status",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Статус платежа:"
            ),
        ),
    ]
