# Generated by Django 5.1.7 on 2025-03-27 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lms_system", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="lesson",
            old_name="course_id",
            new_name="course",
        ),
    ]
