# Generated by Django 5.1.7 on 2025-03-27 20:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lms_system", "0002_rename_course_id_lesson_course"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lesson",
            name="course",
            field=models.ForeignKey(
                help_text="Выберите курс",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lessons",
                to="lms_system.course",
                verbose_name="Курс:",
            ),
        ),
    ]
