# Generated by Django 5.1.7 on 2025-08-01 08:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lms_system", "0004_course_owner_lesson_owner"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        help_text="Укажите курс подписки",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscriptions",
                        to="lms_system.course",
                        verbose_name="Курс подписки:",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="Укажите подписчика",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscribed_courses",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Подписчик:",
                    ),
                ),
            ],
            options={
                "verbose_name": "Подписка",
                "verbose_name_plural": "Подписки",
                "ordering": ["course"],
            },
        ),
    ]
